/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IfJoinGame.java
 *
 * Created on Oct 10, 2011, 7:52:01 PM
 */
package edu.luc.tictactoe.gui.controllerOLD;

import edu.luc.tictactoe.networking.ClientMachine;
import edu.luc.tictactoe.networking.INetworking;

/**
 * @author Paul Stasiuk
 * 
 * The IfJoin Game draws the Join Game form. This form is brought to the user if
 * the user wishes to join a network based gamed.
 *  
 */
public class IfJoinGame extends javax.swing.JFrame {

    /** Creates new form IfJoinGame */
    public IfJoinGame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ipAddressFeild = new javax.swing.JTextField();
        portNumberFeild = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        joinGameBtn = new javax.swing.JButton();
        mainMenuBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(edu.luc.tictactoe.gui.controllerOLD.TicTacToeUIApp.class).getContext().getResourceMap(IfJoinGame.class);
        ipAddressFeild.setText(resourceMap.getString("ipAddressFeild.text")); // NOI18N
        ipAddressFeild.setName("ipAddressFeild"); // NOI18N

        portNumberFeild.setText(resourceMap.getString("portNumberFeild.text")); // NOI18N
        portNumberFeild.setName("portNumberFeild"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        joinGameBtn.setText(resourceMap.getString("joinGameBtn.text")); // NOI18N
        joinGameBtn.setName("joinGameBtn"); // NOI18N
        joinGameBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                joinGameBtnMouseReleased(evt);
            }
        });

        mainMenuBtn.setText(resourceMap.getString("mainMenuBtn.text")); // NOI18N
        mainMenuBtn.setName("mainMenuBtn"); // NOI18N
        mainMenuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mainMenuBtnMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(portNumberFeild, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ipAddressFeild, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(joinGameBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mainMenuBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ipAddressFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addComponent(portNumberFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(joinGameBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainMenuBtn)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 /**
  * If the user wants to go back to the main menu this method is run
  * We close the window 
  * 
  * @param evt
 */   
private void mainMenuBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenuBtnMouseReleased
    this.dispose();
    TicTacToeUIApp.getApplication().getMainFrame().setVisible(true);
}//GEN-LAST:event_mainMenuBtnMouseReleased

/**
 * If the user attempts the join the game after filling out the the IP address and Port, this is the method that is run.
 * 
 * @param evt
 */
private void joinGameBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_joinGameBtnMouseReleased
   
	MainBoard mainBoard= new MainBoard();
	if(!(portNumberFeild.getText().isEmpty() && ipAddressFeild.getText().isEmpty())){
		int port= Integer.valueOf(portNumberFeild.getText());
		String ipAddress= ipAddressFeild.getText();
		
		NetworkUIBridge uiBridge= new NetworkUIBridge(mainBoard);
		INetworking clientMachine= new ClientMachine(ipAddress, port, uiBridge);
		mainBoard.setNetworking(clientMachine,true);
		
		new Thread((Runnable)clientMachine).start();
	    mainBoard.setLocationRelativeTo(this);
	    this.dispose();
	    TicTacToeUIApp.getApplication().show(mainBoard);
	    mainBoard.setResizable(false);
	    mainBoard.setSize(815, 482);
	}
	
	
}//GEN-LAST:event_joinGameBtnMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IfJoinGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IfJoinGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IfJoinGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IfJoinGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new IfJoinGame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ipAddressFeild;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton joinGameBtn;
    private javax.swing.JButton mainMenuBtn;
    private javax.swing.JTextField portNumberFeild;
    // End of variables declaration//GEN-END:variables
}
