/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IfHostMachine.java
 *
 * Created on Oct 10, 2011, 7:51:50 PM
 */
package edu.luc.tictactoe.gui.controller;

import edu.luc.tictactoe.networking.HostMachine;
import edu.luc.tictactoe.networking.INetworking;

/**
 *
 * @author Paul Stasiuk
 * 
 * The IfHostMachine class displays the Host Machine Form.
 * 
 * The Host Machine form is displayed if the user decides to be the host machine in the network based option
 * 
 */
public class IfHostMachine extends javax.swing.JFrame {
	private Thread networkThread;
	private INetworking hostMachine;
	private MainBoard mainBoard;
	
    /** Creates new form IfHostMachine */
    public IfHostMachine() {
    	
        initComponents();
        playBtn.setVisible(false);
        mainBoard= new MainBoard();
        System.out.println("Creating the hostmachine..");
        NetworkUIBridge uiBridge= new NetworkUIBridge(mainBoard);
    	hostMachine= new HostMachine(uiBridge);
    	mainBoard.setNetworking(hostMachine,false);
    	networkThread= new Thread((Runnable) hostMachine);
    	networkThread.start();
    	
    	portNumberLabel.setText("6262");
    	ipaddressLabel.setText(hostMachine.getIpAddress());
    	
    	
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ipAddressTextLabel = new javax.swing.JLabel();
        ipaddressLabel = new javax.swing.JLabel();
        portNumberTextLabel = new javax.swing.JLabel();
        portNumberLabel = new javax.swing.JLabel();
        playBtn = new javax.swing.JButton();
        playBtn.setEnabled(false);
        mainMenuBtn = new javax.swing.JButton();
        waitingText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(edu.luc.tictactoe.gui.controller.TicTacToeUIApp.class).getContext().getResourceMap(IfHostMachine.class);
        ipAddressTextLabel.setText(resourceMap.getString("ipAddressTextLabel.text")); // NOI18N
        ipAddressTextLabel.setName("ipAddressTextLabel"); // NOI18N

        ipaddressLabel.setText(resourceMap.getString("ipaddressLabel.text")); // NOI18N
        ipaddressLabel.setName("ipaddressLabel"); // NOI18N

        portNumberTextLabel.setText(resourceMap.getString("portNumberTextLabel.text")); // NOI18N
        portNumberTextLabel.setName("portNumberTextLabel"); // NOI18N

        portNumberLabel.setText(resourceMap.getString("portNumberLabel.text")); // NOI18N
        portNumberLabel.setName("portNumberLabel"); // NOI18N

        playBtn.setText(resourceMap.getString("playBtn.text")); // NOI18N
        playBtn.setName("playBtn"); // NOI18N
        playBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                playBtnMouseReleased(evt);
            }
        });

        mainMenuBtn.setText(resourceMap.getString("mainMenuBtn.text")); // NOI18N
        mainMenuBtn.setName("mainMenuBtn"); // NOI18N
        mainMenuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mainMenuBtnMouseReleased(evt);
            }
        });

        waitingText.setText(resourceMap.getString("waitingText.text")); // NOI18N
        waitingText.setName("waitingText"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(ipAddressTextLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(ipaddressLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(portNumberTextLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(portNumberLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(playBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mainMenuBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(waitingText)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(ipAddressTextLabel)
                .addGap(18, 18, 18)
                .addComponent(ipaddressLabel)
                .addGap(18, 18, 18)
                .addComponent(portNumberTextLabel)
                .addGap(18, 18, 18)
                .addComponent(portNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(waitingText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(playBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainMenuBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>

/**
 * If the user wants to go back to the main menu this method is run
 * We close the window and interrupt the networking.
 * 
 * @param evt
 */
private void mainMenuBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenuBtnMouseReleased
	this.dispose();
    networkThread.interrupt();
    TicTacToeUIApp.getApplication().getMainFrame().setVisible(true);
}//GEN-LAST:event_mainMenuBtnMouseReleased

/**
 * Once the client has been connected, the user can play the game by selecting the "Play" button.
 * Selecting the Play button runs this method. 
 * 
 * This method creates a new game board, sets the size and allows the user to play the game.
 * @param evt
 */
private void playBtnMouseReleased(java.awt.event.MouseEvent evt) {
	
    mainBoard.setLocationRelativeTo(this);
    this.dispose();
    TicTacToeUIApp.getApplication().show(mainBoard);
    mainBoard.setResizable(false);
    mainBoard.setSize(815, 482);
	
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    	
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IfHostMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IfHostMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IfHostMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IfHostMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new IfHostMachine().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ipAddressTextLabel;
    private javax.swing.JLabel ipaddressLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mainMenuBtn;
    public static javax.swing.JButton playBtn;
    private javax.swing.JLabel portNumberLabel;
    private javax.swing.JLabel portNumberTextLabel;
    public static javax.swing.JLabel waitingText;
    // End of variables declaration//GEN-END:variables
}
