/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IfNetworkBased.java
 *
 * Created on Oct 10, 2011, 7:44:59 PM
 */
package edu.luc.tictactoe.gui.controller;

import javax.swing.JFrame;

/**
 *
 * @author Paul Stasiuk
 * 
 * The IfNetworkBased class displays the IfNetworkBased form. This form lets the user select which type of network
 * based game they wish to play- either the user is the host machine or the cleint machine.
 * 
 */
public class IfNetworkBased extends javax.swing.JFrame {

    /** Creates new form IfNetworkBased */
    public IfNetworkBased() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hostMachineBtn = new javax.swing.JButton();
        joinGameBtn = new javax.swing.JButton();
        mainMenuBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(edu.luc.tictactoe.gui.controller.TicTacToeUIApp.class).getContext().getResourceMap(IfNetworkBased.class);
        hostMachineBtn.setText(resourceMap.getString("hostMachineBtn.text")); // NOI18N
        hostMachineBtn.setName("hostMachineBtn"); // NOI18N
        hostMachineBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                hostMachineBtnMouseReleased(evt);
            }
        });

        joinGameBtn.setText(resourceMap.getString("joinGameBtn.text")); // NOI18N
        joinGameBtn.setName("joinGameBtn"); // NOI18N
        joinGameBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                joinGameBtnMouseReleased(evt);
            }
        });

        mainMenuBtn.setText(resourceMap.getString("mainMenuBtn.text")); // NOI18N
        mainMenuBtn.setName("mainMenuBtn"); // NOI18N
        mainMenuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mainMenuBtnMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hostMachineBtn)
                    .addComponent(joinGameBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(mainMenuBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(hostMachineBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(joinGameBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainMenuBtn)
                .addGap(79, 79, 79))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void mainMenuBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenuBtnMouseReleased
    this.dispose();
    TicTacToeUIApp.getApplication().getMainFrame().setVisible(true);
}//GEN-LAST:event_mainMenuBtnMouseReleased

/**
 * If the user wishes to be the host machine, this method is run.
 * We basically create a new Host Machien form which then starts
 * up the networking from the host side.
 * 
 * @param evt
 */
private void hostMachineBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hostMachineBtnMouseReleased
    //If the user wishes to be the host machine
	
	
	IfHostMachine ifHostMachine= new IfHostMachine();
    ifHostMachine.setLocationRelativeTo(this);
    this.dispose();
    TicTacToeUIApp.getApplication().show(ifHostMachine);
    ifHostMachine.setResizable(false);
    ifHostMachine.setSize(415,300);
}//GEN-LAST:event_hostMachineBtnMouseReleased

/**
 * If the user wants to join a game, then this method is run. 
 * 
 * This method takes the user to a window where they can input the IP address and port and join a game
 * @param evt
 */
private void joinGameBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_joinGameBtnMouseReleased
  
	IfJoinGame ifJoinGame= new IfJoinGame();
    ifJoinGame.setLocationRelativeTo(ifJoinGame);
    
    this.dispose();
    
    TicTacToeUIApp.getApplication().show(ifJoinGame);
    ifJoinGame.setResizable(false);
    ifJoinGame.setSize(340,280);
}//GEN-LAST:event_joinGameBtnMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IfNetworkBased.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IfNetworkBased.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IfNetworkBased.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IfNetworkBased.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new IfNetworkBased().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hostMachineBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton joinGameBtn;
    private javax.swing.JButton mainMenuBtn;
    // End of variables declaration//GEN-END:variables
}
