/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ifPlay.java
 *
 * Created on Oct 8, 2011, 1:25:21 PM
 */
package edu.luc.tictactoe.gui.controller;

import javax.swing.JFrame;

import edu.luc.tictactoe.application.MainApplication;
import edu.luc.tictactoe.businesslogic.implementation.GameType;
import edu.luc.tictactoe.businesslogic.implementation.TicTacToePlay;

/**
 * @author Paul Stasiuk
 * 
 * The IfPlay class draws the form that allows the user to select a Network Based game or a game that that is
 * Played on the host machine.
 * 
 * 
 */
public class IfPlay extends javax.swing.JFrame {
	
    /** Creates new form ifPlay */
    public IfPlay() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        player1Name = new javax.swing.JTextField();
        otmBtn = new javax.swing.JButton();
        nbBtn = new javax.swing.JButton();
        mainMenuBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(edu.luc.tictactoe.gui.controller.TicTacToeUIApp.class).getContext().getResourceMap(IfPlay.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        player1Name.setText(resourceMap.getString("player1Name.text")); // NOI18N
        player1Name.setName("player1Name"); // NOI18N

        otmBtn.setText(resourceMap.getString("otmBtn.text")); // NOI18N
        otmBtn.setName("otmBtn"); // NOI18N
        otmBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                otmBtnMouseReleased(evt);
            }
        });

        nbBtn.setText(resourceMap.getString("nbBtn.text")); // NOI18N
        nbBtn.setName("nbBtn"); // NOI18N
        nbBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nbBtnMouseReleased(evt);
            }
        });

        mainMenuBtn.setText(resourceMap.getString("mainMenuBtn.text")); // NOI18N
        mainMenuBtn.setName("mainMenuBtn"); // NOI18N
        mainMenuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mainMenuBtnMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(player1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(otmBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nbBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(player1Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(otmBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nbBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainMenuBtn)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * If the user wishes to play against another user on this machine, the following method is run.
 * We first check to make sure that the input is not blank, then we go ahead and proceed to show
 * the next windows for the host based game.
 * 
 * @param evt
 */
private void otmBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otmBtnMouseReleased
    //set the player2 name..
    //TO-DO Add code in here to put up a dialog box saying that the player name 
    //is invalid, please enter a new one.
	//TODO AKREM WE NEED TO INITIALIZE THE PLAYERS HERE for on this machine..
	
    String player1NameString= player1Name.getText();
    if(!(player1NameString.isEmpty())){
       
    	MainApplication.ticTacToePlay = new TicTacToePlay(GameType.WithAnotherPersonInSameComputer);
    	MainApplication.ticTacToePlay.setPlayerOne(player1NameString);
    	
       IfOTM ifOtm= new IfOTM();
       JFrame mainFrame = TicTacToeUIApp.getApplication().getMainFrame();
       ifOtm.setLocationRelativeTo(mainFrame);
       //TO-DO Figure out how to close this application window without exiting the whole application
       TicTacToeUIApp.getApplication().show(ifOtm);
       ifOtm.setSize(310,315);
       this.dispose();
    }
    
  
    
}//GEN-LAST:event_otmBtnMouseReleased

/**
 * If the user wishes to go back to the main menu, this method is run
 * 
 * @param evt
 */
private void mainMenuBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenuBtnMouseReleased
    
    this.dispose();
    TicTacToeUIApp.getApplication().getMainFrame().setVisible(true);
}//GEN-LAST:event_mainMenuBtnMouseReleased
/**
 * If the user wants to play a network based game, this method is run.
 * We check to make sure that the inputs are valid, then proceed to the
 * network based windows/forms
 * 
 * @param evt
 */
private void nbBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nbBtnMouseReleased
    //This is where the network based stuff is going to be handled at this point
	
	String player1NameString= player1Name.getText();
	if(!(player1NameString.isEmpty())){
	
		MainApplication.ticTacToePlay = new TicTacToePlay(GameType.WithAnotherPersonInNetwork);
    	MainApplication.ticTacToePlay.setPlayerOne(player1NameString);
    	
		IfNetworkBased ifNetworkBased= new IfNetworkBased();
	    JFrame mainFrame= TicTacToeUIApp.getApplication().getMainFrame();
	    ifNetworkBased.setLocationRelativeTo(mainFrame);
	    this.dispose();
	    TicTacToeUIApp.getApplication().show(ifNetworkBased);
	    ifNetworkBased.setSize(300,280);
	}
    
}//GEN-LAST:event_nbBtnMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IfPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IfPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IfPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IfPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new IfPlay().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mainMenuBtn;
    private javax.swing.JButton nbBtn;
    private javax.swing.JButton otmBtn;
    private javax.swing.JTextField player1Name;
    // End of variables declaration//GEN-END:variables
}
